version: 2.1
executors:
  my-executor:
    docker:
      - image: cimg/ruby:2.7.1-node
    environment:
      BUNDLE_PATH: vendor/bundle

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.1
    executor: my-executor
    environment:
      RAILS_ENV: production
    steps:
      - run: echo Hello Worlds